<a href="https://colab.research.google.com/github/bharathrockstar813-byte/e-commerce-/blob/main/python%20day21.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [4]:
arr1 = np.array([1,2,3])
arr2 = np.array([10,20,30])
print(arr1+arr2)
print(arr2-arr1)
print(arr1*arr2)
print(arr2/arr1)
print(arr1%arr2)
print(arr1**arr2)

[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]
[1 2 3]
[              1         1048576 205891132094649]


In [9]:
l = np.array([10,20,30,40,50,60])
#add elements = sum
print(np.sum(l))
#average
print(np.mean(l))
#max
print(np.max(l))
#min
print(np.min(l))
#stand devetion
print(np.std(l))
#variance
print(np.var(l))
#size of element in an array
print(np.size(l))
#arg max
print(np.argmax(l))
#arg min
print(np.argmin(l))
#applaying square root
print(np.sqrt(l))

210
35.0
60
10
17.07825127659933
291.6666666666667
6
5
0
[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781 7.74596669]


In [11]:
arr=np.array([-1,-2,-3,-4,-5])
print(np.abs(arr))

[1 2 3 4 5]


In [ ]:
#numpy rounding fouction

In [13]:
arr = np.array([1.2,2.7,3.5,4.1,5.9])
print(np.round(arr))

[1. 3. 4. 4. 6.]


In [14]:
arr = np.array([1.2,2.7,3.5,4.1,5.9])
print(np.floor(arr))

[1. 2. 3. 4. 5.]
