<a href="https://colab.research.google.com/github/bharathrockstar813-byte/e-commerce-/blob/main/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello world")

hello world


In [1]:
!pip install numpy

In [6]:
import numpy as np
l =[ 1,2,3,4,5]
print(l)
print("type of list",type(1))
#after converting into list
l = np.array(l)
print(l)
print("type of array",type(l))
print(l.ndim)

[1, 2, 3, 4, 5]
type of list <class 'int'>
[1 2 3 4 5]
type of array <class 'numpy.ndarray'>
1


In [14]:
l1 =[1,2,3,4,5,]
l2 =[3,4,5,0,2]
l3 =[5,0,7,8,9]
l4= np.array ([
   l1,
   l2,
   l3
])
print(l4)
print(l4.ndim)

[[1 2 3 4 5]
 [3 4 5 0 2]
 [5 0 7 8 9]]
2


In [17]:
l1 = [
    [1,2],
    [3,4]
]
l2=[
    [1,2],
    [3,4]
]
l3 = np.array([
    l1,l2
])
print(l3)
print(l3.ndim)

[[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]]
3


In [18]:
l = [1,2,3,4,5]
p = (1,2,3,4,5)
l = np.array(l)
p = np.array(p)
print(l)
print("tuple connect ")
print(p)

[1 2 3 4 5]
tuple connect 
[1 2 3 4 5]


In [ ]:
# fromiter

In [19]:
l = [1,2,3,4,5,]
arr = np.fromiter(l, dtype=int)
print(arr)

[1 2 3 4 5]


In [23]:
l = np.arange(5)
print(l)
l =np.arange(1,9)
print(l)
l = np.arange(1,10,2)
print(l)


[0 1 2 3 4]
[1 2 3 4 5 6 7 8]
[1 3 5 7 9]


In [26]:
arr = np.linspace(1,5,8)
print(arr)


[1.         1.57142857 2.14285714 2.71428571 3.28571429 3.85714286
 4.42857143 5.        ]


In [ ]:
l = np.array([
    [1,2,3,4,5],
    [4,5,6,7],
    [8,9,10,1]
])